#! /bin/sh

sudo mkdir .tmp
sudo mkdir .tmp/gt
sudo chown $(whoami) .tmp/gt

FILES=$(find ./test/ -name "*.gt")
for f in $FILES
do
  echo "Generating test: $f"
  ruby scripts/generate_test_file.rb $f
done