name: MacOS Test Suite

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Install Homebrew
      run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    - name: Set /usr/local permissions
      run: sudo mkdir /usr/local && sudo chown $(whoami) -R /usr/local

    - name: Install autotools
      run: brew install autoconf automake libtool

    - name: autoconf
      run: autoconf

    - name: configure
      run: sudo ./configure

    - name: Apply Permissions
      run: sudo chown $(whoami) -R /usr/local/lib/libcspec* && sudo chown $(whoami) -R /usr/local/include/cspec*

    - name: Cache Libraries
      run: sudo /sbin/ldconfig -v

    - name: make directories
      run: make directories

    - name: generate tests
      run: sh scripts/generate_tests
  
    - name: make tests
      run: make tests

    - name: run tests
      run: ./bin/test_suite