name: Windows Test Suite

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Install MSYS2
      run: choco install msys2

    - name: Build and install tools
      run: C:\tools\msys64\usr\bin\bash -lc "pacman -Sy git tar binutils autoconf make libtool automake p7zip patch gcc"
      env:
        HOME: ${{ runner.workspace }}/gambit
        MINGW_INSTALLS: ${{ matrix.task.installs }}
        CI: true

    - name: Test Autoconf
      run: C:\tools\msys64\usr\bin\bash -lc "autoconf --version"
      env:
        HOME: ${{ runner.workspace }}/gambit
        MINGW_INSTALLS: ${{ matrix.task.installs }}
        CI: true

    - name: Test Make
      run: C:\tools\msys64\usr\bin\bash -lc "make -v"
      env:
        HOME: ${{ runner.workspace }}/gambit
        MINGW_INSTALLS: ${{ matrix.task.installs }}
        CI: true