name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Install MSYS2
      run: choco install msys2

    - name: Build and install tools
      run: C:\tools\msys64\usr\bin\bash -lc "pacman -Sy autoconf make gcc git --noconfirm"
      env:
        HOME: ${{ runner.workspace }}/gambit
        MINGW_INSTALLS: ${{ matrix.task.installs }}
        CI: true

    - name: Test Autoconf
      run: C:\tools\msys64\usr\bin\bash -lc "autoconf --version"
      env:
        HOME: ${{ runner.workspace }}/gambit
        MINGW_INSTALLS: ${{ matrix.task.installs }}
        CI: true

    - name: Test Make
      run: C:\tools\msys64\usr\bin\bash -lc "make -v"
      env:
        HOME: ${{ runner.workspace }}/gambit
        MINGW_INSTALLS: ${{ matrix.task.installs }}
        CI: true

    - name: Test GCC
      run: C:\tools\msys64\usr\bin\bash -lc "gcc -v"
      env:
        HOME: ${{ runner.workspace }}/gambit
        MINGW_INSTALLS: ${{ matrix.task.installs }}
        CI: true

    - name: Test Git
      run: C:\tools\msys64\usr\bin\bash -lc "git --version"
      env:
        HOME: ${{ runner.workspace }}/gambit
        MINGW_INSTALLS: ${{ matrix.task.installs }}
        CI: true

    - name: Autoconf
      run: C:\tools\msys64\usr\bin\bash -lc "autoconf"
      env:
        HOME: ${{ runner.workspace }}/gambit
        MINGW_INSTALLS: ${{ matrix.task.installs }}
        CI: true

    - name: Configure
      run: C:\tools\msys64\usr\bin\bash -lc "./configure"
      env:
        HOME: ${{ runner.workspace }}/gambit
        MINGW_INSTALLS: ${{ matrix.task.installs }}
        CI: true

    - name: Make Directories
      run: C:\tools\msys64\usr\bin\bash -lc "make directories"
      env:
        HOME: ${{ runner.workspace }}/gambit
        MINGW_INSTALLS: ${{ matrix.task.installs }}
        CI: true

