name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Install MSYS2
      run: choco install msys2

    - name: Build and install tools
      run: C:\tools\msys64\usr\bin\bash -lc "pacman -Sy autoconf make gcc git automake libtool ruby --noconfirm"
      env:
        HOME: ${{ runner.workspace }}/gambit
        MINGW_INSTALLS: ${{ matrix.task.installs }}
        CI: true

    - name: Autoconf
      run: C:\tools\msys64\usr\bin\bash -lc "autoconf"
      env:
        HOME: ${{ runner.workspace }}/gambit
        MINGW_INSTALLS: ${{ matrix.task.installs }}
        CI: true

    - name: Configure
      run: C:\tools\msys64\usr\bin\bash -lc "./configure"
      env:
        HOME: ${{ runner.workspace }}/gambit
        MINGW_INSTALLS: ${{ matrix.task.installs }}
        CI: true

    - name: Make Directories
      run: C:\tools\msys64\usr\bin\bash -lc "make directories"
      env:
        HOME: ${{ runner.workspace }}/gambit
        MINGW_INSTALLS: ${{ matrix.task.installs }}
        CI: true

    - name: Generate Tests
      run: C:\tools\msys64\usr\bin\bash -lc "./scripts/windows_generate_tests"
      env:
        HOME: ${{ runner.workspace }}/gambit
        MINGW_INSTALLS: ${{ matrix.task.installs }}
        CI: true

    - name: Make Tests
      run: C:\tools\msys64\usr\bin\bash -lc "make tests"
      env:
        HOME: ${{ runner.workspace }}/gambit
        MINGW_INSTALLS: ${{ matrix.task.installs }}
        CI: true

    - name: Run Test Suite
      run: C:\tools\msys64\usr\bin\bash -lc "./bin/test_suite"
      env:
        HOME: ${{ runner.workspace }}/gambit
        MINGW_INSTALLS: ${{ matrix.task.installs }}
        CI: true